# Test real pack/list/extract/test operations and their resulting bytes.
if(NOT DEFINED UNPACKER OR NOT DEFINED TEST_ROOT)
    message(FATAL_ERROR "UNPACKER and TEST_ROOT are required")
endif()
string(TIMESTAMP stamp "%Y%m%d%H%M%S")
string(RANDOM LENGTH 8 ALPHABET 0123456789abcdef suffix)
set(run "${TEST_ROOT}/${stamp}-${suffix}")
file(MAKE_DIRECTORY "${run}/nested")
file(MAKE_DIRECTORY "${run}/temp")
set(ENV{TEMP} "${run}/temp")
set(ENV{TMP} "${run}/temp")
set(ENV{TMPDIR} "${run}/temp")
file(WRITE "${run}/nested/payload.txt" "XFileUnpacker roundtrip\nsecond line\n")
file(WRITE "${run}/empty.txt" "")
file(WRITE "${run}/xxfc_unpack_test_tmp/keep.txt" "keep this existing directory")

function(run_ok)
    execute_process(COMMAND "${UNPACKER}" ${ARGV} WORKING_DIRECTORY "${run}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${ARGV}: exit ${result}\n${output}\n${error}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()

function(run_error)
    execute_process(COMMAND "${UNPACKER}" ${ARGV} WORKING_DIRECTORY "${run}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0)
        message(FATAL_ERROR "${ARGV}: unexpectedly succeeded\n${output}\n${error}")
    endif()
endfunction()

foreach(container IN ITEMS zip tar cpio tar.gz)
    run_ok(a "sample.${container}" "nested/payload.txt" "empty.txt")
    run_ok(l "sample.${container}")
    if(NOT last_output MATCHES "nested/payload.txt" OR NOT last_output MATCHES "2 member\\(s\\)")
        message(FATAL_ERROR "Listing differs from the sample interface: ${last_output}")
    endif()
    if(last_output MATCHES "Header offset:")
        message(FATAL_ERROR "Normal listing unexpectedly includes advanced metadata: ${last_output}")
    endif()
    run_ok(l "sample.${container}" --advanced)
    if(NOT last_output MATCHES "nested/payload.txt" OR
       NOT last_output MATCHES "Packed size:" OR
       NOT last_output MATCHES "Unpacked size:" OR
       NOT last_output MATCHES "Header offset:" OR
       NOT last_output MATCHES "Data offset:" OR
       NOT last_output MATCHES "2 member\\(s\\)")
        message(FATAL_ERROR "${container}: advanced listing omitted member data: ${last_output}")
    endif()
    set(advanced_output "${last_output}")
    run_ok(l "sample.${container}" -slt)
    if(NOT last_output STREQUAL advanced_output)
        message(FATAL_ERROR "${container}: -slt differs from --advanced")
    endif()
    run_ok(x "sample.${container}" "-oout-${container}")
    file(SHA256 "${run}/nested/payload.txt" expected)
    file(SHA256 "${run}/out-${container}/nested/payload.txt" actual)
    if(NOT expected STREQUAL actual)
        message(FATAL_ERROR "${container}: extracted payload differs")
    endif()
    file(SIZE "${run}/out-${container}/empty.txt" empty_size)
    if(NOT empty_size EQUAL 0)
        message(FATAL_ERROR "${container}: empty file changed")
    endif()
    run_ok(t "sample.${container}")
endforeach()

run_ok(L "sample.zip")
run_ok(X "sample.zip" "-ospace in output")
file(SHA256 "${run}/space in output/nested/payload.txt" actual)
if(NOT expected STREQUAL actual)
    message(FATAL_ERROR "Output path with spaces failed")
endif()
file(WRITE "${run}/nested/данные.txt" "UTF-8 filename and archive path\n")
run_ok(a "архив.zip" "nested/данные.txt")
run_ok(x "архив.zip" "-oраспаковано")
file(SHA256 "${run}/nested/данные.txt" unicode_expected)
file(SHA256 "${run}/распаковано/nested/данные.txt" unicode_actual)
if(NOT unicode_expected STREQUAL unicode_actual)
    message(FATAL_ERROR "Unicode paths failed")
endif()
file(WRITE "${run}/broken.zip" "This is not a ZIP archive")
run_error(l "broken.zip")
run_error(t "broken.zip")
run_error(q "sample.zip")
run_error(e "sample.zip")
run_error(l "missing.zip")
run_error(l "sample.zip" --advanced -slt)
run_error(x "sample.zip" --advanced)
run_error(x "sample.zip" -bad-switch)
run_error(x "sample.zip" -o)
run_error(a "empty.zip")
file(WRITE "${run}/preserve.unsupported" "original archive sentinel")
file(SHA256 "${run}/preserve.unsupported" before)
run_error(a "preserve.unsupported" "empty.txt")
file(SHA256 "${run}/preserve.unsupported" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Unsupported writer truncated the existing file")
endif()
file(SHA256 "${run}/sample.zip" before)
run_error(a "sample.zip" "sample.zip")
file(SHA256 "${run}/sample.zip" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Self-input truncated the archive")
endif()
foreach(frontend IN ITEMS GUI TUI)
    if(DEFINED ${frontend} AND EXISTS "${${frontend}}")
        execute_process(COMMAND "${${frontend}}" --smoke-file-types "sample.tar.gz"
            WORKING_DIRECTORY "${run}" RESULT_VARIABLE result
            OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 25)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${frontend} file type combobox: ${result}\n${output}\n${error}")
        endif()
        foreach(command IN ITEMS l x t a)
            if(command STREQUAL "x")
                set(arguments x "sample.zip" "-oout-${frontend}")
            elseif(command STREQUAL "a")
                set(arguments a "new-${frontend}.zip" "nested/payload.txt" "empty.txt")
            else()
                set(arguments "${command}" "sample.zip")
            endif()
            execute_process(COMMAND "${${frontend}}" --smoke-test ${arguments}
                WORKING_DIRECTORY "${run}" RESULT_VARIABLE result
                OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 25)
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "${frontend} ${arguments}: ${result}\n${output}\n${error}")
            endif()
        endforeach()
        file(SHA256 "${run}/out-${frontend}/nested/payload.txt" actual)
        if(NOT expected STREQUAL actual)
            message(FATAL_ERROR "${frontend}: worker extraction changed payload")
        endif()
        run_ok(x "new-${frontend}.zip" "-onew-out-${frontend}")
        file(SHA256 "${run}/new-out-${frontend}/nested/payload.txt" actual)
        if(NOT expected STREQUAL actual)
            message(FATAL_ERROR "${frontend}: worker archive creation changed payload")
        endif()
    endif()
endforeach()
file(READ "${run}/xxfc_unpack_test_tmp/keep.txt" sentinel)
if(NOT sentinel STREQUAL "keep this existing directory")
    message(FATAL_ERROR "Test damaged a preexisting scratch directory")
endif()
file(GLOB leftovers "${run}/temp/XFileUnpacker_test_*")
if(leftovers)
    message(FATAL_ERROR "Test scratch folders were left behind: ${leftovers}")
endif()
message(STATUS "ZIP, TAR, CPIO, gzip roundtrips and error handling passed")
