execute_process(COMMAND "${UNPACKER}" --formats RESULT_VARIABLE result OUTPUT_VARIABLE plain ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT error STREQUAL "" OR NOT plain MATCHES "Supported file types [(]xxfclib[)]: [0-9]+")
    message(FATAL_ERROR "Cannot list formats: ${result} ${error}")
endif()
string(ASCII 27 escape)
if(plain MATCHES "${escape}")
    message(FATAL_ERROR "Redirected auto output must be plain text")
endif()
foreach(name IN ITEMS BINARY ZIP TAR.GZ PE64 CPX4 "Xamarin compressed assembly"
        "BitRock CookFS installer" "Smart Install Maker" "UPX packed executable"
        "MoleBox SVFS package")
    if(NOT plain MATCHES "${name}")
        message(FATAL_ERROR "Missing format: ${name}")
    endif()
endforeach()
foreach(command IN ITEMS --formats i)
    execute_process(COMMAND "${UNPACKER}" "${command}" --color=never RESULT_VARIABLE result OUTPUT_VARIABLE other)
    if(NOT result EQUAL 0 OR NOT other STREQUAL plain)
        message(FATAL_ERROR "${command} --color=never differs from the catalog")
    endif()
endforeach()
execute_process(COMMAND "${UNPACKER}" --formats --color=always RESULT_VARIABLE result OUTPUT_VARIABLE colored)
if(NOT result EQUAL 0 OR NOT colored MATCHES "${escape}\\[1;36m" OR NOT colored MATCHES "${escape}\\[0;32m")
    message(FATAL_ERROR "Forced colors are missing")
endif()
string(REGEX REPLACE "${escape}\\[[0-9;]*m" "" stripped "${colored}")
if(NOT stripped STREQUAL plain)
    message(FATAL_ERROR "Colored output differs from the catalog")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env NO_COLOR=1 "${UNPACKER}" --formats
    RESULT_VARIABLE result OUTPUT_VARIABLE other)
if(NOT result EQUAL 0 OR NOT other STREQUAL plain)
    message(FATAL_ERROR "NO_COLOR output differs from the catalog")
endif()
execute_process(COMMAND "${UNPACKER}" --formats --color=invalid RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 2 OR NOT error MATCHES "unexpected argument")
    message(FATAL_ERROR "Invalid format-list argument was not rejected")
endif()
