if(NOT DEFINED GUI OR NOT DEFINED TEST_ROOT)
    message(FATAL_ERROR "GUI and TEST_ROOT are required")
endif()
string(RANDOM LENGTH 10 ALPHABET 0123456789abcdef suffix)
set(run "${TEST_ROOT}/${suffix}")
file(MAKE_DIRECTORY "${run}")
string(REPEAT "Threaded extraction payload\n" 2000 payload)
file(WRITE "${run}/payload.txt" "${payload}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf archive.zip --format=zip payload.txt
    WORKING_DIRECTORY "${run}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot create progress fixture")
endif()
file(SHA256 "${run}/payload.txt" expected)
foreach(frontend IN ITEMS GUI TUI)
    if(NOT DEFINED ${frontend})
        continue()
    endif()
    foreach(mode IN ITEMS fast slow cancel)
        execute_process(COMMAND "${${frontend}}" "--smoke-progress-${mode}" x archive.zip "-oout-${frontend}-${mode}"
            WORKING_DIRECTORY "${run}" RESULT_VARIABLE result TIMEOUT 15
            OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(mode STREQUAL "cancel")
            if(NOT result EQUAL 1)
                message(FATAL_ERROR "${frontend} decoder cancellation: ${result}\n${output}\n${error}")
            endif()
        else()
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "${frontend} ${mode} threaded progress: ${result}\n${output}\n${error}")
            endif()
            file(SHA256 "${run}/out-${frontend}-${mode}/payload.txt" actual)
            if(NOT actual STREQUAL expected)
                message(FATAL_ERROR "${frontend} ${mode} extraction changed the payload")
            endif()
        endif()
    endforeach()
endforeach()
