#!/usr/bin/env python3
"""Regenerate platform icons from the same vector geometry (requires Pillow)."""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "icons"
SIZES = (16, 24, 32, 48, 64, 128, 256, 512, 1024)


def generate():
    OUT.mkdir(parents=True, exist_ok=True)
    # Draw large, then downsample for smooth edges even in a 16-pixel taskbar.
    scale = 2
    image = Image.new("RGBA", (1024 * scale, 1024 * scale))
    draw = ImageDraw.Draw(image)
    vector = []

    def polygon(points, color):
        draw.polygon([(x * scale, y * scale) for x, y in points], fill=color)
        vector.append('<polygon points="%s" fill="%s"/>' %
                      (" ".join(f"{x},{y}" for x, y in points), color))

    draw.rounded_rectangle((40 * scale, 40 * scale, 984 * scale, 984 * scale),
                           radius=208 * scale, fill="#183B56")
    vector.append('<rect x="40" y="40" width="944" height="944" rx="208" fill="#183B56"/>')
    # Open box, separated faces, and a broad extraction arrow.
    polygon([(230, 440), (512, 550), (794, 440), (794, 754), (512, 866), (230, 754)], "#EFAF38")
    polygon([(512, 550), (794, 440), (794, 754), (512, 866)], "#CE8225")
    polygon([(230, 440), (512, 330), (794, 440), (512, 550)], "#A35E1B")
    polygon([(230, 440), (512, 550), (358, 663), (136, 548)], "#FFCC66")
    polygon([(512, 550), (794, 440), (888, 548), (666, 663)], "#FFD98B")
    polygon([(468, 432), (556, 432), (556, 296), (654, 296), (512, 144), (370, 296), (468, 296)], "#F5FAFF")
    polygon([(322, 746), (434, 790), (434, 826), (322, 782)], "#FFDA86")
    svg = '<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">\n'
    svg += '<title>XFileUnpacker</title><desc>Open archive box with an extraction arrow</desc>\n'
    (OUT / "xfileunpacker.svg").write_text(svg + "\n".join(vector) + "\n</svg>\n", encoding="utf-8")
    for size in SIZES:
        image.resize((size, size), Image.Resampling.LANCZOS).save(OUT / f"xfileunpacker-{size}.png")
    icon = image.resize((1024, 1024), Image.Resampling.LANCZOS)
    icon.save(OUT / "xfileunpacker.ico", sizes=[(s, s) for s in SIZES if s <= 256])
    icon.save(OUT / "xfileunpacker.icns")
    # The reusable About API accepts copied RGBA pixels, without an image decoder.
    rgba = image.resize((64, 64), Image.Resampling.LANCZOS).tobytes()
    rows = ["    " + ", ".join(f"0x{byte:02x}" for byte in rgba[offset:offset + 16]) + ","
            for offset in range(0, len(rgba), 16)]
    header = "/* Generated by packaging/generate_icons.py. */\n"
    header += "#ifndef XFU_ICON_RGBA_H\n#define XFU_ICON_RGBA_H\n"
    header += "#define XFU_ICON_WIDTH 64\n#define XFU_ICON_HEIGHT 64\n"
    header += "static const unsigned char xfu_icon_rgba[] = {\n" + "\n".join(rows) + "\n};\n#endif\n"
    (OUT / "xfileunpacker_rgba.h").write_text(header, encoding="ascii")


if __name__ == "__main__":
    generate()
