install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/src/formats/sqlite_sql/" DESTINATION share/source/sqlite_sql)
install(FILES "${XFILEUNPACKER_XXFCLIB_DIR}/src/formats/sqlite_sql/PROVENANCE.json" DESTINATION share/licenses/sqlite_sql)
foreach(_native bitrock smart_install_maker molebox)
    install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/src/formats/${_native}/" DESTINATION "share/source/${_native}")
    install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/include/xxfclib/formats/${_native}/" DESTINATION "share/source/${_native}/include")
endforeach()
