install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/src/formats/superdat/" DESTINATION share/source/superdat)
install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/include/xxfclib/formats/superdat/" DESTINATION share/source/superdat/include)
install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/src/formats/excelsior/" DESTINATION share/source/excelsior)
install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/include/xxfclib/formats/excelsior/" DESTINATION share/source/excelsior/include)
install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/src/formats/fead/" DESTINATION share/source/fead)
install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/include/xxfclib/formats/fead/" DESTINATION share/source/fead/include)
install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/src/formats/wim/" DESTINATION share/source/wim)
install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/include/xxfclib/formats/wim/" DESTINATION share/source/wim/include)
install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/src/formats/legacy_archive_engine/" DESTINATION share/source/legacy_archive_engine/native)
install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/include/xxfclib/formats/legacy_archive_engine/" DESTINATION share/source/legacy_archive_engine/include)

install(DIRECTORY "${XFILEUNPACKER_XXFCLIB_DIR}/src/formats/dgca/" DESTINATION share/source/dgca)
